ALTER TABLE users 
DROP COLUMN IF EXISTS display_name,
DROP COLUMN IF EXISTS bio,
DROP COLUMN IF EXISTS avatar_url,
DROP COLUMN IF EXISTS banner_url,
DROP COLUMN IF EXISTS location,
DROP COLUMN IF EXISTS website,
DROP COLUMN IF EXISTS social_links;
