ALTER TABLE users 
ADD COLUMN IF NOT EXISTS display_name VARCHAR(50) DEFAULT '',
ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS banner_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS location VARCHAR(100) DEFAULT '',
ADD COLUMN IF NOT EXISTS website VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '[]'::jsonb;
